#send-flag-message-to-console meaning logging flag messages. if the plugin detect lot's of hackers. It's will spam.
#allow-bypass's permission is "acb.bypass"
send-flag-messaage-to-console: true
allow-bypass: false
punish-settings:
  enable: false
  punish-violations-count: 150
  command: 'minecraft:kick %%player%% hacking'
checks:
  Fly:
    A:
      enable: true
      teleportback: false
    B:
      enable: true
      teleportback: false
    C:
      enable: true
      teleportback: false
    D:
      enable: true
      teleportback: false
    E:
      enable: true
      teleportback: false
  Speed:
    A:
      enable: true
      teleportback: true
    B:
      enable: true
      teleportback: true
    C:
      enable: true
      teleportback: true
  Step:
    enable: true
    teleportback: true
  NoSlow:
    enable: true
    teleportback: true
  InvalidMove:
    enable: true
    teleportback: false
  NoFall:
    enable: true
  Scaffold:
    enable: true
    removeblock: true
  Timer:
    enable: true
    teleportback: true
  KillAura:
    enable: true
    removehit: true
